apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vfvqj40z3-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vfvqj40z3-java-quarkus-gitops